//CAMPGROUNDS
export const GET_CAMPGROUNDS = "GET_CAMPGROUNDS";
export const GET_CAMPGROUND = "GET_CAMPGROUND";
export const GET_USER_CAMPGROUNDS = "GET_USER_CAMPGROUNDS";
export const GET_USERS_CAMPGROUNDS = "GET_USERS_CAMPGROUNDS";
export const UPDATE_CAMPGROUND = "UPDATE_CAMPGROUND";
//USERS
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const GET_CURRENT = "GET_CURRENT";
export const UPDATE = "UPDATE";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPLOAD_USER_IMG = "UPLOAD_USER_IMG";
export const BECOME_ADMIN = "BECOME_ADMIN";
export const ADMIN_GET_USERS = "ADMIN_GET_USERS";
export const SUCCESS = "SUCCESS";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const FAIL = "FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const TOGGLE_LOADING_FALSE = "TOGGLE_LOADING_FALSE";
//COMMENTS
export const GET_COMMENTS = "GET_COMMENTS";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
